name: Complete Continuous Integration - build

on:
  push:
    branches:
      - '**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v3

      - name: setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: run tests with coverage
        run: make cover

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v3

      - name: setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: run tests with coverage
        run: make build

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: chapter-04/final
