name: Complete Continuous Integration - build

on:
  push:
    branches:
      - '**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: setup go environment
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.0'

      - name: run tests with coverage
        run: make cover

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: setup go environment
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.0'

      - name: build
        run: make build

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - uses: actions/checkout@v4
      - name: golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.60.1 && golangci-lint --version && make lint
